name: minglit_iamport_v1
description: "Iamport V1 Payment and Certification package for Minglit."
version: 26.03.435-dev
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  # Iamport V1 SDK
  iamport_flutter: ^0.10.19
  # Web support
  # uni_links or similar might be needed for deep links if iamport_flutter doesn't handle everything.

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
