import 'package:app_user/src/features/consent/providers/consent_providers.dart';
import 'package:app_user/src/routing/app_routes.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:minglit_kit/minglit_kit.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

part 'app_router.g.dart';

/// Root navigator key shared with [BugReporterWrapper] for dialog display.
final rootNavigatorKey = GlobalKey<NavigatorState>();
@riverpod
GoRouter goRouter(Ref ref) {
  final authState = ValueNotifier<AuthState?>(null);

  ref.listen(authStateChangesProvider, (_, next) {
    next.whenData((state) {
      authState.value = state;
    });
  });

  // Pre-fetch consent state so the redirect can read it synchronously.
  ref.watch(hasRequiredConsentsProvider);

  return GoRouter(
    navigatorKey: rootNavigatorKey,
    initialLocation: '/',
    refreshListenable: authState,
    redirect: (context, state) {
      // Supabase SDK에서 직접 읽음 — Riverpod 캐시 갱신 타이밍과 무관하게 정확
      final isLoggedIn = Supabase.instance.client.auth.currentUser != null;
      final isLoggingIn = state.uri.path == '/login';
      final path = state.uri.path;

      // Redirect /explore deep links to home (backward compat)
      if (path.startsWith('/explore')) return '/';

      // Allow dev pages without authentication
      if (path.startsWith('/dev')) return null;

      // 1. 이미 로그인 상태인데 로그인 페이지로 가려면 원래 목적지 또는 홈으로
      if (isLoggedIn && isLoggingIn) {
        final from = state.uri.queryParameters['from'];
        // from 검증: 내부 경로만 허용, 루프 방지
        if (from != null &&
            from.startsWith('/') &&
            !from.startsWith('//') &&
            !from.startsWith('/login')) {
          return from;
        }
        return '/';
      }

      // 2. 보호된 경로 정의 (로그인 필수)
      // prefix-match: 이 경로로 시작하는 모든 진입은 로그인을 요구함
      const protectedPrefixes = [
        '/my', // 마이페이지, 알림 설정 (/my/notification-settings)
        '/tickets/my', // 내 티켓 목록
        '/payment', // 결제 관련
        '/purchase-history', // 구매 내역
        '/certification', // 본인인증
      ];

      // suffix-match: 경로 끝이 /apply 인 경우 (이벤트 신청)
      final isProtected =
          protectedPrefixes.any(path.startsWith) || path.endsWith('/apply');

      // 3. 비로그인 상태에서 보호된 경로 진입 시 -> 로그인 페이지로
      if (!isLoggedIn && isProtected) {
        // 로그인 후 원래 가려던 곳으로 돌아오기 위해 쿼리 파라미터 추가
        return Uri(path: '/login', queryParameters: {'from': path}).toString();
      }

      // Fix #883: 필수 동의 미완료 유저를 /signup/consent로 리다이렉트
      if (isLoggedIn && path != '/signup/consent') {
        final consentAsync = ref.read(hasRequiredConsentsProvider);
        // AsyncLoading → skip (prevent infinite redirect while loading)
        if (!consentAsync.isLoading) {
          final hasConsents = consentAsync.value;
          if (hasConsents == false) {
            return '/signup/consent';
          }
        }
      }

      // Fix #883: 동의 완료 후 /signup/consent에 머무르고 있으면 홈으로
      if (isLoggedIn && path == '/signup/consent') {
        final consentAsync = ref.read(hasRequiredConsentsProvider);
        if (consentAsync.value == true) {
          return '/';
        }
      }

      return null;
    },
    routes: $appRoutes, // Generated by go_router_builder
    observers: [MinglitNavigationObserver()],
  );
}
