import 'package:app_user/src/routing/app_routes.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:minglit_kit/minglit_kit.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'app_router.g.dart';

/// Root navigator key shared with [BugReporterWrapper] for dialog display.
final rootNavigatorKey = GlobalKey<NavigatorState>();

@riverpod
GoRouter goRouter(Ref ref) {
  final routerRefresh = ValueNotifier<int>(0);

  void refreshRouter() {
    routerRefresh.value++;
  }

  ref.listen(authStateChangesProvider, (_, _) {
    refreshRouter();
  });
  ref.listen(hasRequiredConsentsProvider, (_, _) {
    refreshRouter();
  });

  final router = GoRouter(
    navigatorKey: rootNavigatorKey,
    initialLocation: '/',
    refreshListenable: routerRefresh,
    redirect: (context, state) {
      final path = state.uri.path;
      final location = state.uri.toString();
      final isLoggedIn = ref.read(currentUserProvider) != null;
      final isLoggingIn = path == '/login';
      final isConsentPage = path == '/signup/consent';
      final consentState = ref.read(hasRequiredConsentsProvider);

      // Redirect /explore deep links to home (backward compat)
      if (path.startsWith('/explore')) return '/';

      // Allow dev pages without authentication
      if (path.startsWith('/dev')) return null;

      // 1. 이미 로그인 상태인데 로그인 페이지로 가려면 원래 목적지 또는 홈으로
      if (isLoggedIn && isLoggingIn) {
        return _sanitizeReturnLocation(
              state.uri.queryParameters['from'],
              allowConsentPage: true,
            ) ??
            '/';
      }

      // 2. 보호된 경로 정의 (로그인 필수)
      // prefix-match: 이 경로로 시작하는 모든 진입은 로그인을 요구함
      const protectedPrefixes = [
        '/my', // 마이페이지, 알림 설정 (/my/notification-settings)
        '/tickets/my', // 내 티켓 목록
        '/payment', // 결제 관련
        '/purchase-history', // 구매 내역
        '/certification', // 본인인증
        '/signup/consent', // 필수 동의
      ];

      // suffix-match: 경로 끝이 /apply 인 경우 (이벤트 신청)
      final isProtected =
          protectedPrefixes.any(path.startsWith) || path.endsWith('/apply');

      // 3. 비로그인 상태에서 보호된 경로 진입 시 -> 로그인 페이지로
      if (!isLoggedIn && isProtected) {
        // 로그인 후 원래 가려던 곳으로 돌아오기 위해 쿼리 파라미터 추가
        return Uri(
          path: '/login',
          queryParameters: {'from': location},
        ).toString();
      }

      // 4. Consent lookup failure must fail closed on protected routes.
      // Fix #883: When retrying after error, isLoading && hasError are both
      // true — check hasError first so retrying doesn't bypass fail-closed.
      if (consentState.hasError) {
        if (isProtected && !isConsentPage) {
          return Uri(
            path: '/signup/consent',
            queryParameters: {'from': location},
          ).toString();
        }

        return null;
      }

      // 5. 동의 상태 로딩 중(초기 로드, 이전 상태 없음)에는 redirect를 건너뛰어 루프를 방지
      if (consentState.isLoading) {
        return null;
      }

      final hasRequiredConsents = consentState.asData?.value ?? false;

      // 5. 로그인 상태에서 보호된 경로 접근 시 필수 동의가 없으면 동의 페이지로
      if (!hasRequiredConsents && isProtected && !isConsentPage) {
        return Uri(
          path: '/signup/consent',
          queryParameters: {'from': location},
        ).toString();
      }

      // 6. 이미 필수 동의를 마친 상태에서 동의 페이지에 오면 원래 목적지로 복귀
      if (hasRequiredConsents && isConsentPage) {
        return _sanitizeReturnLocation(state.uri.queryParameters['from']) ??
            '/';
      }

      return null;
    },
    routes: $appRoutes, // Generated by go_router_builder
    observers: [MinglitNavigationObserver()],
  );

  ref.onDispose(() {
    router.dispose();
    routerRefresh.dispose();
  });

  return router;
}

String? _sanitizeReturnLocation(
  String? location, {
  bool allowConsentPage = false,
}) {
  if (location == null || location.isEmpty) return null;
  if (!location.startsWith('/') || location.startsWith('//')) return null;

  final uri = Uri.tryParse(location);
  final path = uri?.path ?? location;
  if (path == '/login') return null;
  if (!allowConsentPage && path == '/signup/consent') return null;

  return location;
}
