// coverage.ts — LCOV 파싱 → markdown 리포트 생성
//
// 사용:
//   deno run --allow-read --allow-write _coverage/coverage.ts \
//     --lcov=coverage.lcov --out=_coverage/coverage-report.md

import { parseArgs } from "jsr:@std/cli@1/parse-args";

interface FileCoverage {
  path: string;
  ef: string;                        // EF 이름 (디렉토리 명)
  linesHit: number;
  linesTotal: number;
  pct: number;
}

interface EFCoverage {
  ef: string;
  files: FileCoverage[];
  linesHit: number;
  linesTotal: number;
  pct: number;
}

function parseLcov(lcov: string): FileCoverage[] {
  const files: FileCoverage[] = [];
  let current: { path: string; hit: number; total: number } | null = null;

  for (const line of lcov.split("\n")) {
    if (line.startsWith("SF:")) {
      current = { path: line.slice(3).trim(), hit: 0, total: 0 };
    } else if (line.startsWith("LH:") && current) {
      current.hit = parseInt(line.slice(3), 10);
    } else if (line.startsWith("LF:") && current) {
      current.total = parseInt(line.slice(3), 10);
    } else if (line.startsWith("end_of_record") && current) {
      const ef = extractEf(current.path);
      const pct = current.total > 0 ? (current.hit / current.total) * 100 : 0;
      files.push({ path: current.path, ef, linesHit: current.hit, linesTotal: current.total, pct });
      current = null;
    }
  }
  return files;
}

/** functions/<ef>/<file>.ts → ef. _ prefix 디렉토리 (테스트 util) 는 제외 대상 */
function extractEf(path: string): string {
  const m = path.match(/functions\/([^/]+)\//);
  if (!m) return "_unknown";
  return m[1];
}

function groupByEf(files: FileCoverage[]): EFCoverage[] {
  const map = new Map<string, EFCoverage>();
  for (const f of files) {
    if (f.ef.startsWith("_")) continue;          // _shared / _test_utils / _coverage 등 제외
    if (f.path.endsWith("_test.ts")) continue;   // 테스트 파일 자신 제외
    let entry = map.get(f.ef);
    if (!entry) {
      entry = { ef: f.ef, files: [], linesHit: 0, linesTotal: 0, pct: 0 };
      map.set(f.ef, entry);
    }
    entry.files.push(f);
    entry.linesHit += f.linesHit;
    entry.linesTotal += f.linesTotal;
  }
  for (const e of map.values()) {
    e.pct = e.linesTotal > 0 ? (e.linesHit / e.linesTotal) * 100 : 0;
  }
  return [...map.values()].sort((a, b) => a.pct - b.pct);   // 낮은 coverage 먼저
}

function renderMarkdown(efs: EFCoverage[]): string {
  const totalHit = efs.reduce((s, e) => s + e.linesHit, 0);
  const totalLines = efs.reduce((s, e) => s + e.linesTotal, 0);
  const totalPct = totalLines > 0 ? (totalHit / totalLines) * 100 : 0;
  const generated = new Date().toISOString();

  const rows = efs.map((e) => {
    const icon = e.pct >= 90 ? "🟢" : e.pct >= 70 ? "🟡" : "🔴";
    return `| ${icon} | ${e.ef} | ${e.pct.toFixed(1)}% | ${e.linesHit}/${e.linesTotal} | ${e.files.length} |`;
  }).join("\n");

  return `<!-- AUTO-GENERATED by .github/workflows/monitor-deno-coverage.yml. DO NOT EDIT. -->

# Deno EF Unit Test Coverage

**Generated**: \`${generated}\`
**Overall**: ${totalPct.toFixed(1)}% (${totalHit}/${totalLines} lines covered across ${efs.length} EFs)

## Per-EF Coverage (sorted by % asc — lowest first)

|   | EF | Coverage | Lines | Files |
|---|---|---|---|---|
${rows}

## Legend

- 🟢 ≥90%  /  🟡 70-89%  /  🔴 <70%
- Lines = hit/total (non-test .ts files only)
- 본 리포트는 \`supabase/functions/**\` push to dev 마다 자동 갱신 (\`[skip ci]\`)
- PR diff coverage (변경 라인 ≥90%) 는 \`pr-gate.yml\` 의 \`test-edge-functions\` 잡 별도 gate
`;
}

async function main() {
  const args = parseArgs(Deno.args, {
    string: ["lcov", "out"],
    default: { lcov: "coverage.lcov", out: "_coverage/coverage-report.md" },
  });

  const lcov = await Deno.readTextFile(args.lcov);
  const files = parseLcov(lcov);
  const efs = groupByEf(files);
  const md = renderMarkdown(efs);
  await Deno.writeTextFile(args.out, md);

  console.log(`✅ Wrote ${args.out} — ${efs.length} EFs, ${files.length} files`);
}

if (import.meta.main) {
  await main();
}
