BEGIN;
SELECT plan(179);

-- partners
SELECT has_table('partners');
SELECT has_column('partners', 'id');
SELECT has_column('partners', 'name');
SELECT has_column('partners', 'introduction');
SELECT has_column('partners', 'address');
SELECT has_column('partners', 'contact_phone');
SELECT has_column('partners', 'contact_email');
SELECT has_column('partners', 'representative_name');
SELECT has_column('partners', 'biz_name');
SELECT has_column('partners', 'biz_number');
SELECT has_column('partners', 'profile_image_url');
SELECT has_column('partners', 'is_active');
SELECT has_column('partners', 'created_at');
SELECT has_column('partners', 'updated_at');
SELECT col_type_is('partners', 'id', 'uuid');
SELECT col_is_pk('partners', 'id');
SELECT col_has_default('partners', 'id');
SELECT col_not_null('partners', 'id');
SELECT col_not_null('partners', 'name');
SELECT col_has_default('partners', 'is_active');
SELECT col_type_is('partners', 'created_at', 'timestamp with time zone');
SELECT col_has_default('partners', 'created_at');
SELECT col_type_is('partners', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('partners', 'updated_at');

-- partner_settlements
SELECT has_table('partner_settlements');
SELECT has_column('partner_settlements', 'partner_id');
SELECT has_column('partner_settlements', 'biz_type');
SELECT has_column('partner_settlements', 'biz_name');
SELECT has_column('partner_settlements', 'biz_number');
SELECT has_column('partner_settlements', 'representative_name');
SELECT has_column('partner_settlements', 'bank_name');
SELECT has_column('partner_settlements', 'account_number');
SELECT has_column('partner_settlements', 'account_holder');
SELECT has_column('partner_settlements', 'tax_email');
SELECT has_column('partner_settlements', 'biz_registration_path');
SELECT has_column('partner_settlements', 'bankbook_path');
SELECT has_column('partner_settlements', 'updated_at');
SELECT col_type_is('partner_settlements', 'partner_id', 'uuid');
SELECT col_is_pk('partner_settlements', 'partner_id');
SELECT col_is_fk('partner_settlements', 'partner_id');
SELECT col_not_null('partner_settlements', 'partner_id');
SELECT col_type_is('partner_settlements', 'biz_type', 'business_type');
SELECT col_not_null('partner_settlements', 'biz_type');
SELECT col_not_null('partner_settlements', 'biz_name');
SELECT col_not_null('partner_settlements', 'biz_number');
SELECT col_not_null('partner_settlements', 'representative_name');
SELECT col_not_null('partner_settlements', 'bank_name');
SELECT col_not_null('partner_settlements', 'account_number');
SELECT col_not_null('partner_settlements', 'account_holder');
SELECT col_type_is('partner_settlements', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('partner_settlements', 'updated_at');

-- partner_member_permissions
SELECT has_table('partner_member_permissions');
SELECT has_column('partner_member_permissions', 'id');
SELECT has_column('partner_member_permissions', 'partner_id');
SELECT has_column('partner_member_permissions', 'user_id');
SELECT has_column('partner_member_permissions', 'role');
SELECT has_column('partner_member_permissions', 'permissions');
SELECT has_column('partner_member_permissions', 'joined_at');
SELECT col_type_is('partner_member_permissions', 'id', 'uuid');
SELECT col_is_pk('partner_member_permissions', 'id');
SELECT col_has_default('partner_member_permissions', 'id');
SELECT col_not_null('partner_member_permissions', 'id');
SELECT col_type_is('partner_member_permissions', 'partner_id', 'uuid');
SELECT col_is_fk('partner_member_permissions', 'partner_id');
SELECT col_not_null('partner_member_permissions', 'partner_id');
SELECT col_type_is('partner_member_permissions', 'user_id', 'uuid');
SELECT col_is_fk('partner_member_permissions', 'user_id');
SELECT col_not_null('partner_member_permissions', 'user_id');
SELECT col_type_is('partner_member_permissions', 'role', 'partner_role');
SELECT col_not_null('partner_member_permissions', 'role');
SELECT col_has_default('partner_member_permissions', 'role');
SELECT col_not_null('partner_member_permissions', 'permissions');
SELECT col_has_default('partner_member_permissions', 'permissions');
SELECT col_type_is('partner_member_permissions', 'joined_at', 'timestamp with time zone');
SELECT col_has_default('partner_member_permissions', 'joined_at');

-- partner_applications
SELECT has_table('partner_applications');
SELECT has_column('partner_applications', 'id');
SELECT has_column('partner_applications', 'user_id');
SELECT has_column('partner_applications', 'status');
SELECT has_column('partner_applications', 'brand_name');
SELECT has_column('partner_applications', 'introduction');
SELECT has_column('partner_applications', 'address');
SELECT has_column('partner_applications', 'contact_phone');
SELECT has_column('partner_applications', 'contact_email');
SELECT has_column('partner_applications', 'biz_type');
SELECT has_column('partner_applications', 'biz_name');
SELECT has_column('partner_applications', 'biz_number');
SELECT has_column('partner_applications', 'representative_name');
SELECT has_column('partner_applications', 'bank_name');
SELECT has_column('partner_applications', 'account_number');
SELECT has_column('partner_applications', 'account_holder');
SELECT has_column('partner_applications', 'tax_email');
SELECT has_column('partner_applications', 'biz_registration_path');
SELECT has_column('partner_applications', 'bankbook_path');
SELECT has_column('partner_applications', 'admin_comment');
SELECT has_column('partner_applications', 'created_at');
SELECT has_column('partner_applications', 'updated_at');
SELECT col_type_is('partner_applications', 'id', 'uuid');
SELECT col_is_pk('partner_applications', 'id');
SELECT col_has_default('partner_applications', 'id');
SELECT col_not_null('partner_applications', 'id');
SELECT col_type_is('partner_applications', 'user_id', 'uuid');
SELECT col_is_fk('partner_applications', 'user_id');
SELECT col_not_null('partner_applications', 'user_id');
SELECT col_type_is('partner_applications', 'status', 'partner_application_status');
SELECT col_not_null('partner_applications', 'status');
SELECT col_has_default('partner_applications', 'status');
SELECT col_not_null('partner_applications', 'brand_name');
SELECT col_type_is('partner_applications', 'biz_type', 'business_type');
SELECT col_not_null('partner_applications', 'biz_type');
SELECT col_not_null('partner_applications', 'biz_name');
SELECT col_not_null('partner_applications', 'biz_number');
SELECT col_not_null('partner_applications', 'representative_name');
SELECT col_not_null('partner_applications', 'bank_name');
SELECT col_not_null('partner_applications', 'account_number');
SELECT col_not_null('partner_applications', 'account_holder');
SELECT col_not_null('partner_applications', 'biz_registration_path');
SELECT col_not_null('partner_applications', 'bankbook_path');
SELECT col_type_is('partner_applications', 'created_at', 'timestamp with time zone');
SELECT col_has_default('partner_applications', 'created_at');
SELECT col_type_is('partner_applications', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('partner_applications', 'updated_at');

-- locations
SELECT has_table('locations');
SELECT has_column('locations', 'id');
SELECT has_column('locations', 'partner_id');
SELECT has_column('locations', 'name');
SELECT has_column('locations', 'address');
SELECT has_column('locations', 'address_detail');
SELECT has_column('locations', 'region_1');
SELECT has_column('locations', 'region_2');
SELECT has_column('locations', 'region_3');
SELECT has_column('locations', 'directions_guide');
SELECT has_column('locations', 'postal_code');
SELECT has_column('locations', 'geo_point');
SELECT has_column('locations', 'created_at');
SELECT has_column('locations', 'updated_at');
SELECT col_type_is('locations', 'id', 'uuid');
SELECT col_is_pk('locations', 'id');
SELECT col_has_default('locations', 'id');
SELECT col_not_null('locations', 'id');
SELECT col_type_is('locations', 'partner_id', 'uuid');
SELECT col_is_fk('locations', 'partner_id');
SELECT col_not_null('locations', 'partner_id');
SELECT col_not_null('locations', 'name');
SELECT col_not_null('locations', 'address');
SELECT col_type_is('locations', 'created_at', 'timestamp with time zone');
SELECT col_has_default('locations', 'created_at');
SELECT col_not_null('locations', 'created_at');
SELECT col_type_is('locations', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('locations', 'updated_at');
SELECT col_not_null('locations', 'updated_at');
SELECT has_index('locations', 'locations_geo_point_idx');

-- verifications
SELECT has_table('verifications');
SELECT has_column('verifications', 'id');
SELECT has_column('verifications', 'partner_id');
SELECT has_column('verifications', 'category');
SELECT has_column('verifications', 'internal_name');
SELECT has_column('verifications', 'display_name');
SELECT has_column('verifications', 'description');
SELECT has_column('verifications', 'icon_key');
SELECT has_column('verifications', 'form_schema');
SELECT has_column('verifications', 'is_active');
SELECT has_column('verifications', 'created_at');
SELECT col_type_is('verifications', 'id', 'uuid');
SELECT col_is_pk('verifications', 'id');
SELECT col_has_default('verifications', 'id');
SELECT col_not_null('verifications', 'id');
SELECT col_type_is('verifications', 'partner_id', 'uuid');
SELECT col_is_fk('verifications', 'partner_id');
SELECT col_type_is('verifications', 'category', 'verification_category');
SELECT col_not_null('verifications', 'category');
SELECT col_not_null('verifications', 'internal_name');
SELECT col_not_null('verifications', 'display_name');
SELECT col_type_is('verifications', 'form_schema', 'jsonb');
SELECT col_not_null('verifications', 'form_schema');
SELECT col_has_default('verifications', 'form_schema');
SELECT col_has_default('verifications', 'is_active');
SELECT col_type_is('verifications', 'created_at', 'timestamp with time zone');
SELECT col_has_default('verifications', 'created_at');

SELECT * FROM finish();
ROLLBACK;
