BEGIN;
SELECT plan(214);

-- parties
SELECT has_table('parties');
SELECT has_column('parties', 'id');
SELECT has_column('parties', 'partner_id');
SELECT has_column('parties', 'location_id');
SELECT has_column('parties', 'title');
SELECT has_column('parties', 'description');
SELECT has_column('parties', 'image_urls');
SELECT has_column('parties', 'contact_options');
SELECT has_column('parties', 'required_verification_ids');
SELECT has_column('parties', 'min_confirmed_count');
SELECT has_column('parties', 'max_participants');
SELECT has_column('parties', 'status');
SELECT has_column('parties', 'created_at');
SELECT has_column('parties', 'updated_at');
SELECT col_type_is('parties', 'id', 'uuid');
SELECT col_is_pk('parties', 'id');
SELECT col_has_default('parties', 'id');
SELECT col_not_null('parties', 'id');
SELECT col_type_is('parties', 'partner_id', 'uuid');
SELECT col_is_fk('parties', 'partner_id');
SELECT col_not_null('parties', 'partner_id');
SELECT col_type_is('parties', 'location_id', 'uuid');
SELECT col_is_fk('parties', 'location_id');
SELECT col_not_null('parties', 'title');
SELECT col_type_is('parties', 'description', 'jsonb');
SELECT col_type_is('parties', 'contact_options', 'jsonb');
SELECT col_has_default('parties', 'contact_options');
SELECT col_has_default('parties', 'image_urls');
SELECT col_has_default('parties', 'required_verification_ids');
SELECT col_not_null('parties', 'min_confirmed_count');
SELECT col_has_default('parties', 'min_confirmed_count');
SELECT col_not_null('parties', 'max_participants');
SELECT col_has_default('parties', 'max_participants');
SELECT col_not_null('parties', 'status');
SELECT col_has_default('parties', 'status');
SELECT col_type_is('parties', 'created_at', 'timestamp with time zone');
SELECT col_has_default('parties', 'created_at');
SELECT col_not_null('parties', 'created_at');
SELECT col_type_is('parties', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('parties', 'updated_at');
SELECT col_not_null('parties', 'updated_at');

-- party_embeddings
SELECT has_table('party_embeddings');
SELECT has_column('party_embeddings', 'party_id');
SELECT has_column('party_embeddings', 'embedding');
SELECT has_column('party_embeddings', 'updated_at');
SELECT col_type_is('party_embeddings', 'party_id', 'uuid');
SELECT col_is_pk('party_embeddings', 'party_id');
SELECT col_is_fk('party_embeddings', 'party_id');
SELECT col_not_null('party_embeddings', 'party_id');
SELECT col_type_is('party_embeddings', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('party_embeddings', 'updated_at');
SELECT has_index('party_embeddings', 'party_embeddings_embedding_idx');

-- events
SELECT has_table('events');
SELECT has_column('events', 'id');
SELECT has_column('events', 'party_id');
SELECT has_column('events', 'location_id');
SELECT has_column('events', 'title');
SELECT has_column('events', 'description');
SELECT has_column('events', 'image_urls');
SELECT has_column('events', 'contact_options');
SELECT has_column('events', 'start_time');
SELECT has_column('events', 'end_time');
SELECT has_column('events', 'min_confirmed_count');
SELECT has_column('events', 'max_participants');
SELECT has_column('events', 'current_participants');
SELECT has_column('events', 'status');
SELECT has_column('events', 'created_at');
SELECT has_column('events', 'updated_at');
SELECT col_type_is('events', 'id', 'uuid');
SELECT col_is_pk('events', 'id');
SELECT col_has_default('events', 'id');
SELECT col_not_null('events', 'id');
SELECT col_type_is('events', 'party_id', 'uuid');
SELECT col_is_fk('events', 'party_id');
SELECT col_not_null('events', 'party_id');
SELECT col_type_is('events', 'location_id', 'uuid');
SELECT col_is_fk('events', 'location_id');
SELECT col_type_is('events', 'description', 'jsonb');
SELECT col_type_is('events', 'contact_options', 'jsonb');
SELECT col_has_default('events', 'contact_options');
SELECT col_type_is('events', 'start_time', 'timestamp with time zone');
SELECT col_not_null('events', 'start_time');
SELECT col_type_is('events', 'end_time', 'timestamp with time zone');
SELECT col_not_null('events', 'end_time');
SELECT col_not_null('events', 'min_confirmed_count');
SELECT col_has_default('events', 'min_confirmed_count');
SELECT col_not_null('events', 'max_participants');
SELECT col_has_default('events', 'max_participants');
SELECT col_not_null('events', 'current_participants');
SELECT col_has_default('events', 'current_participants');
SELECT col_not_null('events', 'status');
SELECT col_has_default('events', 'status');
SELECT col_type_is('events', 'created_at', 'timestamp with time zone');
SELECT col_has_default('events', 'created_at');
SELECT col_not_null('events', 'created_at');
SELECT col_type_is('events', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('events', 'updated_at');
SELECT col_not_null('events', 'updated_at');

-- entry_group_templates
SELECT has_table('entry_group_templates');
SELECT has_column('entry_group_templates', 'id');
SELECT has_column('entry_group_templates', 'party_id');
SELECT has_column('entry_group_templates', 'label');
SELECT has_column('entry_group_templates', 'gender');
SELECT has_column('entry_group_templates', 'birth_year_min');
SELECT has_column('entry_group_templates', 'birth_year_max');
SELECT has_column('entry_group_templates', 'required_verification_ids');
SELECT has_column('entry_group_templates', 'created_at');
SELECT has_column('entry_group_templates', 'updated_at');
SELECT col_type_is('entry_group_templates', 'id', 'uuid');
SELECT col_is_pk('entry_group_templates', 'id');
SELECT col_has_default('entry_group_templates', 'id');
SELECT col_not_null('entry_group_templates', 'id');
SELECT col_type_is('entry_group_templates', 'party_id', 'uuid');
SELECT col_is_fk('entry_group_templates', 'party_id');
SELECT col_not_null('entry_group_templates', 'party_id');
SELECT col_type_is('entry_group_templates', 'gender', 'gender');
SELECT col_has_default('entry_group_templates', 'required_verification_ids');
SELECT col_type_is('entry_group_templates', 'created_at', 'timestamp with time zone');
SELECT col_has_default('entry_group_templates', 'created_at');
SELECT col_not_null('entry_group_templates', 'created_at');
SELECT col_type_is('entry_group_templates', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('entry_group_templates', 'updated_at');
SELECT col_not_null('entry_group_templates', 'updated_at');

-- entry_groups
SELECT has_table('entry_groups');
SELECT has_column('entry_groups', 'id');
SELECT has_column('entry_groups', 'event_id');
SELECT has_column('entry_groups', 'label');
SELECT has_column('entry_groups', 'gender');
SELECT has_column('entry_groups', 'birth_year_min');
SELECT has_column('entry_groups', 'birth_year_max');
SELECT has_column('entry_groups', 'required_verification_ids');
SELECT has_column('entry_groups', 'created_at');
SELECT has_column('entry_groups', 'updated_at');
SELECT col_type_is('entry_groups', 'id', 'uuid');
SELECT col_is_pk('entry_groups', 'id');
SELECT col_has_default('entry_groups', 'id');
SELECT col_not_null('entry_groups', 'id');
SELECT col_type_is('entry_groups', 'event_id', 'uuid');
SELECT col_is_fk('entry_groups', 'event_id');
SELECT col_not_null('entry_groups', 'event_id');
SELECT col_type_is('entry_groups', 'gender', 'gender');
SELECT col_has_default('entry_groups', 'required_verification_ids');
SELECT col_type_is('entry_groups', 'created_at', 'timestamp with time zone');
SELECT col_has_default('entry_groups', 'created_at');
SELECT col_not_null('entry_groups', 'created_at');
SELECT col_type_is('entry_groups', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('entry_groups', 'updated_at');
SELECT col_not_null('entry_groups', 'updated_at');

-- ticket_templates
SELECT has_table('ticket_templates');
SELECT has_column('ticket_templates', 'id');
SELECT has_column('ticket_templates', 'party_id');
SELECT has_column('ticket_templates', 'name');
SELECT has_column('ticket_templates', 'description');
SELECT has_column('ticket_templates', 'price');
SELECT has_column('ticket_templates', 'quantity');
SELECT has_column('ticket_templates', 'target_entry_group_ids');
SELECT has_column('ticket_templates', 'required_verification_ids');
SELECT has_column('ticket_templates', 'created_at');
SELECT has_column('ticket_templates', 'updated_at');
SELECT col_type_is('ticket_templates', 'id', 'uuid');
SELECT col_is_pk('ticket_templates', 'id');
SELECT col_has_default('ticket_templates', 'id');
SELECT col_not_null('ticket_templates', 'id');
SELECT col_type_is('ticket_templates', 'party_id', 'uuid');
SELECT col_is_fk('ticket_templates', 'party_id');
SELECT col_not_null('ticket_templates', 'party_id');
SELECT col_not_null('ticket_templates', 'name');
SELECT col_not_null('ticket_templates', 'price');
SELECT col_has_default('ticket_templates', 'price');
SELECT col_not_null('ticket_templates', 'quantity');
SELECT col_has_default('ticket_templates', 'target_entry_group_ids');
SELECT col_has_default('ticket_templates', 'required_verification_ids');
SELECT col_type_is('ticket_templates', 'created_at', 'timestamp with time zone');
SELECT col_has_default('ticket_templates', 'created_at');
SELECT col_not_null('ticket_templates', 'created_at');
SELECT col_type_is('ticket_templates', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('ticket_templates', 'updated_at');
SELECT col_not_null('ticket_templates', 'updated_at');

-- tickets
SELECT has_table('tickets');
SELECT has_column('tickets', 'id');
SELECT has_column('tickets', 'event_id');
SELECT has_column('tickets', 'name');
SELECT has_column('tickets', 'description');
SELECT has_column('tickets', 'price');
SELECT has_column('tickets', 'quantity');
SELECT has_column('tickets', 'sold_count');
SELECT has_column('tickets', 'target_entry_group_ids');
SELECT has_column('tickets', 'required_verification_ids');
SELECT has_column('tickets', 'status');
SELECT has_column('tickets', 'created_at');
SELECT has_column('tickets', 'updated_at');
SELECT col_type_is('tickets', 'id', 'uuid');
SELECT col_is_pk('tickets', 'id');
SELECT col_has_default('tickets', 'id');
SELECT col_not_null('tickets', 'id');
SELECT col_type_is('tickets', 'event_id', 'uuid');
SELECT col_is_fk('tickets', 'event_id');
SELECT col_not_null('tickets', 'event_id');
SELECT col_not_null('tickets', 'name');
SELECT col_not_null('tickets', 'price');
SELECT col_has_default('tickets', 'price');
SELECT col_not_null('tickets', 'quantity');
SELECT col_not_null('tickets', 'sold_count');
SELECT col_has_default('tickets', 'sold_count');
SELECT col_has_default('tickets', 'target_entry_group_ids');
SELECT col_has_default('tickets', 'required_verification_ids');
SELECT col_not_null('tickets', 'status');
SELECT col_has_default('tickets', 'status');
SELECT col_type_is('tickets', 'created_at', 'timestamp with time zone');
SELECT col_has_default('tickets', 'created_at');
SELECT col_not_null('tickets', 'created_at');
SELECT col_type_is('tickets', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('tickets', 'updated_at');
SELECT col_not_null('tickets', 'updated_at');

SELECT * FROM finish();
ROLLBACK;
