BEGIN;
SELECT plan(173);

-- event_applications
SELECT has_table('event_applications');
SELECT has_column('event_applications', 'id');
SELECT has_column('event_applications', 'event_id');
SELECT has_column('event_applications', 'ticket_id');
SELECT has_column('event_applications', 'user_id');
SELECT has_column('event_applications', 'status');
SELECT has_column('event_applications', 'message');
SELECT has_column('event_applications', 'payment_id');
SELECT has_column('event_applications', 'payment_amount');
SELECT has_column('event_applications', 'refund_status');
SELECT has_column('event_applications', 'created_at');
SELECT has_column('event_applications', 'updated_at');
SELECT has_column('event_applications', 'rejection_reason');
SELECT col_type_is('event_applications', 'id', 'uuid');
SELECT col_is_pk('event_applications', 'id');
SELECT col_has_default('event_applications', 'id');
SELECT col_not_null('event_applications', 'id');
SELECT col_type_is('event_applications', 'event_id', 'uuid');
SELECT col_is_fk('event_applications', 'event_id');
SELECT col_not_null('event_applications', 'event_id');
SELECT col_type_is('event_applications', 'ticket_id', 'uuid');
SELECT col_is_fk('event_applications', 'ticket_id');
SELECT col_not_null('event_applications', 'ticket_id');
SELECT col_type_is('event_applications', 'user_id', 'uuid');
SELECT col_is_fk('event_applications', 'user_id');
SELECT col_not_null('event_applications', 'user_id');
SELECT col_not_null('event_applications', 'status');
SELECT col_has_default('event_applications', 'status');
SELECT col_has_default('event_applications', 'refund_status');
SELECT col_type_is('event_applications', 'created_at', 'timestamp with time zone');
SELECT col_has_default('event_applications', 'created_at');
SELECT col_not_null('event_applications', 'created_at');
SELECT col_type_is('event_applications', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('event_applications', 'updated_at');
SELECT col_not_null('event_applications', 'updated_at');

-- verification_submissions
SELECT has_table('verification_submissions');
SELECT has_column('verification_submissions', 'id');
SELECT has_column('verification_submissions', 'partner_id');
SELECT has_column('verification_submissions', 'user_id');
SELECT has_column('verification_submissions', 'verification_id');
SELECT has_column('verification_submissions', 'application_id');
SELECT has_column('verification_submissions', 'status');
SELECT has_column('verification_submissions', 'snapshot_data');
SELECT has_column('verification_submissions', 'admin_comment');
SELECT has_column('verification_submissions', 'reviewed_at');
SELECT has_column('verification_submissions', 'reviewed_by');
SELECT has_column('verification_submissions', 'created_at');
SELECT has_column('verification_submissions', 'updated_at');
SELECT col_type_is('verification_submissions', 'id', 'uuid');
SELECT col_is_pk('verification_submissions', 'id');
SELECT col_has_default('verification_submissions', 'id');
SELECT col_not_null('verification_submissions', 'id');
SELECT col_type_is('verification_submissions', 'partner_id', 'uuid');
SELECT col_is_fk('verification_submissions', 'partner_id');
SELECT col_not_null('verification_submissions', 'partner_id');
SELECT col_type_is('verification_submissions', 'user_id', 'uuid');
SELECT col_is_fk('verification_submissions', 'user_id');
SELECT col_not_null('verification_submissions', 'user_id');
SELECT col_type_is('verification_submissions', 'verification_id', 'uuid');
SELECT col_is_fk('verification_submissions', 'verification_id');
SELECT col_not_null('verification_submissions', 'verification_id');
SELECT col_type_is('verification_submissions', 'application_id', 'uuid');
SELECT col_is_fk('verification_submissions', 'application_id');
SELECT col_type_is('verification_submissions', 'status', 'verification_status');
SELECT col_not_null('verification_submissions', 'status');
SELECT col_has_default('verification_submissions', 'status');
SELECT col_type_is('verification_submissions', 'snapshot_data', 'jsonb');
SELECT col_not_null('verification_submissions', 'snapshot_data');
SELECT col_type_is('verification_submissions', 'reviewed_at', 'timestamp with time zone');
SELECT col_type_is('verification_submissions', 'reviewed_by', 'uuid');
SELECT col_is_fk('verification_submissions', 'reviewed_by');
SELECT col_type_is('verification_submissions', 'created_at', 'timestamp with time zone');
SELECT col_has_default('verification_submissions', 'created_at');
SELECT col_type_is('verification_submissions', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('verification_submissions', 'updated_at');
SELECT has_index('verification_submissions', 'verification_submissions_application_id_idx');

-- user_verifications
SELECT has_table('user_verifications');
SELECT has_column('user_verifications', 'id');
SELECT has_column('user_verifications', 'user_id');
SELECT has_column('user_verifications', 'verification_id');
SELECT has_column('user_verifications', 'data');
SELECT has_column('user_verifications', 'updated_at');
SELECT col_type_is('user_verifications', 'id', 'uuid');
SELECT col_is_pk('user_verifications', 'id');
SELECT col_has_default('user_verifications', 'id');
SELECT col_not_null('user_verifications', 'id');
SELECT col_type_is('user_verifications', 'user_id', 'uuid');
SELECT col_is_fk('user_verifications', 'user_id');
SELECT col_not_null('user_verifications', 'user_id');
SELECT col_type_is('user_verifications', 'verification_id', 'uuid');
SELECT col_is_fk('user_verifications', 'verification_id');
SELECT col_not_null('user_verifications', 'verification_id');
SELECT col_type_is('user_verifications', 'data', 'jsonb');
SELECT col_not_null('user_verifications', 'data');
SELECT col_has_default('user_verifications', 'data');
SELECT col_type_is('user_verifications', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('user_verifications', 'updated_at');

-- partner_verified_users
SELECT has_table('partner_verified_users');
SELECT has_column('partner_verified_users', 'partner_id');
SELECT has_column('partner_verified_users', 'user_id');
SELECT has_column('partner_verified_users', 'verification_id');
SELECT has_column('partner_verified_users', 'submission_id');
SELECT has_column('partner_verified_users', 'verified_at');
SELECT has_column('partner_verified_users', 'valid_until');
SELECT col_type_is('partner_verified_users', 'partner_id', 'uuid');
SELECT col_is_fk('partner_verified_users', 'partner_id');
SELECT col_not_null('partner_verified_users', 'partner_id');
SELECT col_type_is('partner_verified_users', 'user_id', 'uuid');
SELECT col_is_fk('partner_verified_users', 'user_id');
SELECT col_not_null('partner_verified_users', 'user_id');
SELECT col_type_is('partner_verified_users', 'verification_id', 'uuid');
SELECT col_is_fk('partner_verified_users', 'verification_id');
SELECT col_not_null('partner_verified_users', 'verification_id');
SELECT col_type_is('partner_verified_users', 'submission_id', 'uuid');
SELECT col_is_fk('partner_verified_users', 'submission_id');
SELECT col_not_null('partner_verified_users', 'submission_id');
SELECT col_type_is('partner_verified_users', 'verified_at', 'timestamp with time zone');
SELECT col_has_default('partner_verified_users', 'verified_at');
SELECT col_type_is('partner_verified_users', 'valid_until', 'timestamp with time zone');
SELECT has_pk('partner_verified_users');

-- event_participants
SELECT has_table('event_participants');
SELECT has_column('event_participants', 'id');
SELECT has_column('event_participants', 'event_id');
SELECT has_column('event_participants', 'ticket_id');
SELECT has_column('event_participants', 'user_id');
SELECT has_column('event_participants', 'application_id');
SELECT has_column('event_participants', 'status');
SELECT has_column('event_participants', 'ticket_code');
SELECT has_column('event_participants', 'created_at');
SELECT has_column('event_participants', 'updated_at');
SELECT col_type_is('event_participants', 'id', 'uuid');
SELECT col_is_pk('event_participants', 'id');
SELECT col_has_default('event_participants', 'id');
SELECT col_not_null('event_participants', 'id');
SELECT col_type_is('event_participants', 'event_id', 'uuid');
SELECT col_is_fk('event_participants', 'event_id');
SELECT col_not_null('event_participants', 'event_id');
SELECT col_type_is('event_participants', 'ticket_id', 'uuid');
SELECT col_is_fk('event_participants', 'ticket_id');
SELECT col_not_null('event_participants', 'ticket_id');
SELECT col_type_is('event_participants', 'user_id', 'uuid');
SELECT col_is_fk('event_participants', 'user_id');
SELECT col_not_null('event_participants', 'user_id');
SELECT col_type_is('event_participants', 'application_id', 'uuid');
SELECT col_is_fk('event_participants', 'application_id');
SELECT col_not_null('event_participants', 'status');
SELECT col_has_default('event_participants', 'status');
SELECT col_type_is('event_participants', 'created_at', 'timestamp with time zone');
SELECT col_has_default('event_participants', 'created_at');
SELECT col_not_null('event_participants', 'created_at');
SELECT col_type_is('event_participants', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('event_participants', 'updated_at');
SELECT col_not_null('event_participants', 'updated_at');

-- verification_comments
SELECT has_table('verification_comments');
SELECT has_column('verification_comments', 'id');
SELECT has_column('verification_comments', 'submission_id');
SELECT has_column('verification_comments', 'author_id');
SELECT has_column('verification_comments', 'content');
SELECT has_column('verification_comments', 'created_at');
SELECT col_type_is('verification_comments', 'id', 'uuid');
SELECT col_is_pk('verification_comments', 'id');
SELECT col_has_default('verification_comments', 'id');
SELECT col_not_null('verification_comments', 'id');
SELECT col_type_is('verification_comments', 'submission_id', 'uuid');
SELECT col_is_fk('verification_comments', 'submission_id');
SELECT col_not_null('verification_comments', 'submission_id');
SELECT col_type_is('verification_comments', 'author_id', 'uuid');
SELECT col_is_fk('verification_comments', 'author_id');
SELECT col_not_null('verification_comments', 'author_id');
SELECT col_type_is('verification_comments', 'content', 'jsonb');
SELECT col_not_null('verification_comments', 'content');
SELECT col_type_is('verification_comments', 'created_at', 'timestamp with time zone');
SELECT col_has_default('verification_comments', 'created_at');

SELECT * FROM finish();
ROLLBACK;
