include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - minglit_lints
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
