codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        flags:
          - minglit-kit
    patch:
      default:
        target: 80%
        threshold: 5%
        flags:
          - minglit-kit
      apps:
        informational: true
        flags:
          - app-user
          - app-partner

comment:
  layout: "condensed_header, diff, flags, condensed_files, condensed_footer"
  behavior: default
  require_changes: true

flags:
  app-user:
    paths:
      - apps/app_user/lib/
    carryforward: true
  app-partner:
    paths:
      - apps/app_partner/lib/
    carryforward: true
  minglit-kit:
    paths:
      - shared/packages/minglit_kit/lib/
    carryforward: true
  backend-integration:
    paths:
      - tests/backend_integration/lib/
    carryforward: true
