import 'dart:async';
import 'dart:convert';

import 'package:app_partner/src/features/checkin/checkin_controller.dart';
import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:minglit_kit/minglit_kit.dart';
import 'package:mocktail/mocktail.dart';

import '../../../utils/mocks.dart';
import '../../../utils/test_utils.dart';

/// Minimal valid TicketToken JSON for processQR tests.
String _makeQrPayload({
  String ticketId = 'ticket-001',
  String eventId = 'event-001',
  String userId = 'user-abcd',
  String signature = 'sig',
  DateTime? expiresAt,
}) {
  final exp = (expiresAt ?? DateTime.now().add(const Duration(days: 7)))
      .toIso8601String();
  // TicketToken.fromJson expects camelCase keys (generated by json_serializable).
  return jsonEncode({
    'ticketId': ticketId,
    'eventId': eventId,
    'userId': userId,
    'signature': signature,
    'expiresAt': exp,
  });
}

/// A deterministic fake Ed25519 public key for tests (crypto ops are mocked).
final _fakePublicKey = SimplePublicKey(
  List.filled(32, 0),
  type: KeyPairType.ed25519,
);

/// A fake TicketToken for mocktail fallback registration.
final _fakeTicketToken = TicketToken.fromJson(
  jsonDecode(_makeQrPayload()) as Map<String, dynamic>,
);

void main() {
  group('CheckinController', () {
    // ── data class tests (existing) ──────────────────────────────────────

    test('initial state is idle with no message or userName', () {
      final container = createContainer();
      final state = container.read(checkinControllerProvider);

      expect(state.result, CheckinResult.idle);
      expect(state.message, isNull);
      expect(state.userName, isNull);
    });

    test('CheckinState copyWith updates individual fields', () {
      const original = CheckinState(result: CheckinResult.idle);

      final updated = original.copyWith(
        result: CheckinResult.success,
        userName: 'User 1234',
      );

      expect(updated.result, CheckinResult.success);
      expect(updated.userName, 'User 1234');
      expect(updated.message, isNull);
    });

    test('CheckinState copyWith preserves unchanged fields', () {
      const original = CheckinState(
        result: CheckinResult.invalid,
        message: '유효하지 않은 티켓입니다.',
      );

      final updated = original.copyWith(result: CheckinResult.idle);

      expect(updated.result, CheckinResult.idle);
      expect(updated.message, '유효하지 않은 티켓입니다.');
    });

    test('CheckinState copyWith without args returns same values', () {
      const original = CheckinState(
        result: CheckinResult.error,
        message: 'err',
        userName: 'John',
      );

      final copy = original.copyWith();

      expect(copy.result, CheckinResult.error);
      expect(copy.message, 'err');
      expect(copy.userName, 'John');
    });

    test('CheckinResult enum has all expected values', () {
      expect(
        CheckinResult.values,
        containsAll([
          CheckinResult.idle,
          CheckinResult.processing,
          CheckinResult.success,
          CheckinResult.alreadyCheckedIn,
          CheckinResult.invalid,
          CheckinResult.error,
        ]),
      );
    });

    // ── processQR behaviour tests ─────────────────────────────────────────
    //
    // processQR는 내부에 3초 피드백 딜레이가 있어 완료까지 ~3초가 걸린다.
    // 각 테스트는 10초 타임아웃을 설정한다.
    // 중간 상태는 provider listener로 캡처한다.

    group('processQR', () {
      late MockCheckinRepository mockRepo;

      // Fix #1288: TicketToken 및 SimplePublicKey에 대한 mocktail fallback 등록.
      // setUpAll에 등록해야 any(named: 'token') matcher가 올바르게 동작한다.
      setUpAll(() {
        registerFallbackValue(_fakePublicKey);
        registerFallbackValue(_fakeTicketToken);
      });

      setUp(() {
        mockRepo = MockCheckinRepository();
        when(
          () => mockRepo.fetchServerPublicKey(),
        ).thenAnswer((_) async => _fakePublicKey);
      });

      ProviderContainer makeContainer() => createContainer(
        overrides: [
          checkinRepositoryProvider.overrideWithValue(mockRepo),
        ],
      );

      // Fix #1288: processQR 성공 경로 — 유효한 QR로 success 상태 전환 검증
      test(
        '성공 — 유효한 QR 데이터로 success 상태 전환 후 idle 복귀',
        () async {
          when(
            () => mockRepo.verifyAndCheckin(
              token: any(named: 'token'),
              serverPublicKey: any(named: 'serverPublicKey'),
            ),
          ).thenAnswer((_) async => true);

          final container = makeContainer();
          final capturedStates = <CheckinState>[];
          container.listen(
            checkinControllerProvider,
            (_, s) => capturedStates.add(s),
          );

          await container
              .read(checkinControllerProvider.notifier)
              .processQR(_makeQrPayload(userId: 'user-abcdef'));

          // 상태 시퀀스: processing → success → idle
          final results = capturedStates.map((s) => s.result).toList();
          expect(
            results,
            containsAllInOrder([
              CheckinResult.processing,
              CheckinResult.success,
              CheckinResult.idle,
            ]),
          );

          // success 시점의 userName은 userId 앞 4자리로 구성됨
          final successState = capturedStates.firstWhere(
            (s) => s.result == CheckinResult.success,
          );
          expect(successState.userName, 'User user');
        },
        timeout: const Timeout(Duration(seconds: 10)),
      );

      // Fix #1288: processQR 실패 경로 — 서버 검증 실패 시 invalid 상태 검증
      test(
        '검증 실패 — verifyAndCheckin false 반환 시 invalid 상태 전환',
        () async {
          when(
            () => mockRepo.verifyAndCheckin(
              token: any(named: 'token'),
              serverPublicKey: any(named: 'serverPublicKey'),
            ),
          ).thenAnswer((_) async => false);

          final container = makeContainer();
          final capturedStates = <CheckinState>[];
          container.listen(
            checkinControllerProvider,
            (_, s) => capturedStates.add(s),
          );

          await container
              .read(checkinControllerProvider.notifier)
              .processQR(_makeQrPayload());

          final results = capturedStates.map((s) => s.result).toList();
          expect(
            results,
            containsAllInOrder([
              CheckinResult.processing,
              CheckinResult.invalid,
            ]),
          );

          final invalidState = capturedStates.firstWhere(
            (s) => s.result == CheckinResult.invalid,
          );
          expect(invalidState.message, '유효하지 않은 티켓입니다.');
        },
        timeout: const Timeout(Duration(seconds: 10)),
      );

      // Fix #1288: processQR JSON 파싱 실패 경로 — malformed QR는 invalid 상태 검증
      test(
        'JSON 파싱 실패 — malformed QR 데이터는 invalid 상태 전환, repo 미호출',
        () async {
          final container = makeContainer();
          final capturedStates = <CheckinState>[];
          container.listen(
            checkinControllerProvider,
            (_, s) => capturedStates.add(s),
          );

          await container
              .read(checkinControllerProvider.notifier)
              .processQR('not-valid-json{{{{');

          final results = capturedStates.map((s) => s.result).toList();
          expect(
            results,
            containsAllInOrder([
              CheckinResult.processing,
              CheckinResult.invalid,
            ]),
          );

          final invalidState = capturedStates.firstWhere(
            (s) => s.result == CheckinResult.invalid,
          );
          expect(invalidState.message, '티켓 데이터를 읽을 수 없습니다.');

          // JSON 파싱 실패 시 repo는 호출되지 않아야 함
          verifyNever(() => mockRepo.fetchServerPublicKey());
        },
        timeout: const Timeout(Duration(seconds: 10)),
      );

      // Fix #1288: processQR 중복 호출 방지 — processing 중 재호출은 무시 검증
      test(
        '중복 호출 방지 — processing 중에는 재호출이 무시됨',
        () async {
          // fetchServerPublicKey는 completer로 첫 번째 호출을 blocking 상태로 유지
          final serverKeyCompleter = Completer<SimplePublicKey>();
          when(
            () => mockRepo.fetchServerPublicKey(),
          ).thenAnswer((_) => serverKeyCompleter.future);
          when(
            () => mockRepo.verifyAndCheckin(
              token: any(named: 'token'),
              serverPublicKey: any(named: 'serverPublicKey'),
            ),
          ).thenAnswer((_) async => true);

          final container = makeContainer();
          // 리스너 등록으로 auto-dispose 방지 — async 공백에서 provider 유지 필요
          container.listen(
            checkinControllerProvider,
            (_, __) {},
          );
          final notifier = container.read(checkinControllerProvider.notifier);

          // 첫 번째 호출 시작 — fetchServerPublicKey에서 blocking
          final firstFuture = notifier.processQR(_makeQrPayload());

          // 마이크로태스크 실행 — state=processing까지 진행
          await Future<void>.delayed(Duration.zero);

          expect(
            container.read(checkinControllerProvider).result,
            CheckinResult.processing,
          );

          // 두 번째 호출 — processing 상태이므로 즉시 반환, repo 추가 호출 없음
          await notifier.processQR(_makeQrPayload());

          // fetchServerPublicKey는 첫 번째 호출에서만 1회 호출됨
          verify(() => mockRepo.fetchServerPublicKey()).called(1);

          // 정리: 첫 번째 호출 완료 (3초 딜레이 포함)
          serverKeyCompleter.complete(_fakePublicKey);
          await firstFuture;
        },
        timeout: const Timeout(Duration(seconds: 10)),
      );

      // Fix #1288: processQR 에러 경로 — fetchServerPublicKey 예외 시 invalid 상태 검증
      test(
        '서버 키 fetch 실패 — 예외 발생 시 invalid 상태 전환',
        () async {
          when(
            () => mockRepo.fetchServerPublicKey(),
          ).thenThrow(StateError('Server public key not configured'));

          final container = makeContainer();
          final capturedStates = <CheckinState>[];
          container.listen(
            checkinControllerProvider,
            (_, s) => capturedStates.add(s),
          );

          await container
              .read(checkinControllerProvider.notifier)
              .processQR(_makeQrPayload());

          final results = capturedStates.map((s) => s.result).toList();
          expect(
            results,
            containsAllInOrder([
              CheckinResult.processing,
              CheckinResult.invalid,
            ]),
          );

          final invalidState = capturedStates.firstWhere(
            (s) => s.result == CheckinResult.invalid,
          );
          expect(invalidState.message, '티켓 데이터를 읽을 수 없습니다.');
        },
        timeout: const Timeout(Duration(seconds: 10)),
      );

      // Fix #1288: verifyAndCheckin 예외 경로 — 런타임 에러 시 invalid 상태 검증
      test(
        'verifyAndCheckin 예외 — 네트워크 에러 시 invalid 상태 전환',
        () async {
          when(
            () => mockRepo.verifyAndCheckin(
              token: any(named: 'token'),
              serverPublicKey: any(named: 'serverPublicKey'),
            ),
          ).thenThrow(Exception('Network timeout'));

          final container = makeContainer();
          final capturedStates = <CheckinState>[];
          container.listen(
            checkinControllerProvider,
            (_, s) => capturedStates.add(s),
          );

          await container
              .read(checkinControllerProvider.notifier)
              .processQR(_makeQrPayload());

          final results = capturedStates.map((s) => s.result).toList();
          expect(
            results,
            containsAllInOrder([
              CheckinResult.processing,
              CheckinResult.invalid,
            ]),
          );

          final invalidState = capturedStates.firstWhere(
            (s) => s.result == CheckinResult.invalid,
          );
          expect(invalidState.message, '티켓 데이터를 읽을 수 없습니다.');
        },
        timeout: const Timeout(Duration(seconds: 10)),
      );

      // Fix #1288: 상태 리셋 — processQR 완료 후 idle로 자동 복귀 검증
      test(
        '상태 리셋 — processQR 완료 후 idle 복귀, userName/message 초기화',
        () async {
          when(
            () => mockRepo.verifyAndCheckin(
              token: any(named: 'token'),
              serverPublicKey: any(named: 'serverPublicKey'),
            ),
          ).thenAnswer((_) async => true);

          final container = makeContainer();
          // 리스너 등록으로 auto-dispose 방지 — 3초 딜레이 동안 provider 유지 필요
          final capturedStates = <CheckinState>[];
          container.listen(
            checkinControllerProvider,
            (_, s) => capturedStates.add(s),
          );
          await container
              .read(checkinControllerProvider.notifier)
              .processQR(_makeQrPayload(userId: 'user-test99'));

          // processQR 완료 후 최종 상태는 idle이며 필드가 초기화되어야 함
          final finalState = container.read(checkinControllerProvider);
          expect(finalState.result, CheckinResult.idle);
          expect(finalState.userName, isNull);
          expect(finalState.message, isNull);
        },
        timeout: const Timeout(Duration(seconds: 10)),
      );

      // Fix #1288: 연속 체크인 — 첫 번째 완료 후 두 번째 사용자 체크인 성공 검증
      test(
        '연속 체크인 — 첫 번째 완료 후 두 번째 사용자 QR 처리 성공',
        () async {
          when(
            () => mockRepo.verifyAndCheckin(
              token: any(named: 'token'),
              serverPublicKey: any(named: 'serverPublicKey'),
            ),
          ).thenAnswer((_) async => true);

          final container = makeContainer();
          // 리스너 등록으로 auto-dispose 방지 — 두 번의 processQR 동안 provider 유지 필요
          container.listen(
            checkinControllerProvider,
            (_, __) {},
          );
          final notifier = container.read(checkinControllerProvider.notifier);

          // 첫 번째 사용자 체크인 완료
          await notifier.processQR(_makeQrPayload(userId: 'user-aaaa11'));
          expect(
            container.read(checkinControllerProvider).result,
            CheckinResult.idle,
          );

          // 두 번째 사용자 체크인 — 상태 덮어쓰기 검증
          final capturedStates = <CheckinState>[];
          container.listen(
            checkinControllerProvider,
            (_, s) => capturedStates.add(s),
          );

          await notifier.processQR(_makeQrPayload(userId: 'user-bbbb22'));

          final successState = capturedStates.firstWhere(
            (s) => s.result == CheckinResult.success,
          );
          // 두 번째 사용자의 userName이 반영됨
          expect(successState.userName, 'User user');
        },
        timeout: const Timeout(Duration(seconds: 20)),
      );
    });
  });
}
