BEGIN;
SELECT plan(53);
SET search_path TO storage, public, extensions;

-- buckets
SELECT has_table('buckets');
SELECT has_column('buckets', 'id');
SELECT has_column('buckets', 'name');
SELECT has_column('buckets', 'owner');
SELECT has_column('buckets', 'created_at');
SELECT has_column('buckets', 'updated_at');
SELECT has_column('buckets', 'public');
SELECT has_column('buckets', 'avif_autodetection');
SELECT has_column('buckets', 'file_size_limit');
SELECT has_column('buckets', 'allowed_mime_types');
SELECT has_column('buckets', 'owner_id');
SELECT has_column('buckets', 'type');
SELECT col_is_pk('buckets', 'id');
SELECT col_not_null('buckets', 'id');
SELECT col_not_null('buckets', 'name');
SELECT col_type_is('buckets', 'owner', 'uuid');
SELECT col_type_is('buckets', 'created_at', 'timestamp with time zone');
SELECT col_has_default('buckets', 'created_at');
SELECT col_type_is('buckets', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('buckets', 'updated_at');
SELECT col_has_default('buckets', 'public');
SELECT col_has_default('buckets', 'avif_autodetection');
SELECT col_type_is('buckets', 'type', 'buckettype');
SELECT col_not_null('buckets', 'type');
SELECT col_has_default('buckets', 'type');

-- objects
SELECT has_table('objects');
SELECT has_column('objects', 'id');
SELECT has_column('objects', 'bucket_id');
SELECT has_column('objects', 'name');
SELECT has_column('objects', 'owner');
SELECT has_column('objects', 'created_at');
SELECT has_column('objects', 'updated_at');
SELECT has_column('objects', 'last_accessed_at');
SELECT has_column('objects', 'metadata');
SELECT has_column('objects', 'path_tokens');
SELECT has_column('objects', 'version');
SELECT has_column('objects', 'owner_id');
SELECT has_column('objects', 'user_metadata');
SELECT col_type_is('objects', 'id', 'uuid');
SELECT col_is_pk('objects', 'id');
SELECT col_has_default('objects', 'id');
SELECT col_not_null('objects', 'id');
SELECT col_is_fk('objects', 'bucket_id');
SELECT col_type_is('objects', 'owner', 'uuid');
SELECT col_type_is('objects', 'created_at', 'timestamp with time zone');
SELECT col_has_default('objects', 'created_at');
SELECT col_type_is('objects', 'updated_at', 'timestamp with time zone');
SELECT col_has_default('objects', 'updated_at');
SELECT col_type_is('objects', 'last_accessed_at', 'timestamp with time zone');
SELECT col_has_default('objects', 'last_accessed_at');
SELECT col_type_is('objects', 'metadata', 'jsonb');
SELECT col_type_is('objects', 'user_metadata', 'jsonb');
SELECT has_index('objects', 'idx_objects_bucket_id_name');

SELECT * FROM finish();
ROLLBACK;
