import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:minglit_kit/src/data/models/party.dart';
import 'package:minglit_kit/src/data/models/party_entry_group.dart';
import 'package:minglit_kit/src/data/models/ticket.dart';

part 'event.freezed.dart';
part 'event.g.dart';

/// **Event Model**
///
/// Represents an actual instance of a party.
@freezed
abstract class Event with _$Event {
  /// Creates an [Event] with core scheduling and capacity data.
  const factory Event({
    required String id,
    @JsonKey(name: 'party_id') required String partyId,
    @JsonKey(name: 'start_time') required DateTime startTime,
    @JsonKey(name: 'end_time') required DateTime endTime,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
    @JsonKey(name: 'location_id') String? locationId,
    String? title,
    Map<String, dynamic>? description,
    @JsonKey(name: 'image_urls') List<String>? imageUrls,
    @JsonKey(name: 'contact_options')
    @Default({})
    Map<String, dynamic> contactOptions,
    @JsonKey(name: 'min_confirmed_count') @Default(0) int minConfirmedCount,
    @JsonKey(name: 'max_participants') @Default(20) int maxParticipants,
    @JsonKey(name: 'current_participants') @Default(0) int currentParticipants,
    @Default('scheduled') String status,
    @JsonKey(includeToJson: false) Location? location,
    @JsonKey(includeToJson: false) Party? party,
    @JsonKey(includeToJson: false) List<Ticket>? tickets,
    @JsonKey(includeToJson: false) List<EntryGroup>? entryGroups,
  }) = _Event;
  const Event._();

  /// Creates an [Event] from a JSON map.
  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);

  /// Creates a fresh Event instance from a Party template.
  factory Event.createFromParty(
    Party party, {
    required DateTime startTime,
    required DateTime endTime,
  }) {
    final now = DateTime.now();
    return Event(
      id: '', // Generated by server
      partyId: party.id,
      startTime: startTime,
      endTime: endTime,
      createdAt: now,
      updatedAt: now,
      locationId: party.locationId,
      title: party.title,
      description: party.description != null
          ? Map<String, dynamic>.from(party.description!)
          : null,
      contactOptions: Map<String, dynamic>.from(party.contactOptions),
      minConfirmedCount: party.minConfirmedCount,
      maxParticipants: party.maxParticipants,
      entryGroups: party.entryGroups
          ?.map(EntryGroup.createFromTemplate)
          .toList(),
    );
  }

  /// Returns image URLs from the event or its party template.
  List<String> get effectiveImageUrls {
    final urls = imageUrls;
    if (urls != null && urls.isNotEmpty) {
      return urls;
    }
    return party?.imageUrls ?? [];
  }

  /// Returns the first available image URL, if any.
  String? get imageUrl => effectiveImageUrls.firstOrNull;
}

/// Convenience helpers for rendering [Event] conditions.
extension EventX on Event {
  /// Summarizes entry conditions for display.
  List<String> get conditionSummaries {
    final groups = entryGroups ?? [];
    if (groups.isEmpty) return ['조건 없음'];

    return groups.map((group) {
      final gender = group.gender;
      final verifIds = group.requiredVerificationIds;

      var genderText = '성별 무관';
      if (gender == 'male') {
        genderText = '남성';
      } else if (gender == 'female') {
        genderText = '여성';
      }

      var birthYearText = '나이 무관';
      final min = group.birthYearMin;
      final max = group.birthYearMax;
      if (min != null && max != null) {
        birthYearText = '$min~$max년생';
      } else if (min != null) {
        birthYearText = '$min년생 이후';
      } else if (max != null) {
        birthYearText = '$max년생 이전';
      }

      String base;
      if (genderText == '성별 무관' && birthYearText == '나이 무관') {
        base = '조건 없음';
      } else if (birthYearText == '나이 무관') {
        base = genderText;
      } else if (genderText == '성별 무관') {
        base = birthYearText;
      } else {
        base = '$genderText ($birthYearText)';
      }

      // Handle label (e.g., "Student Group (Male (1997~2006))")
      final label = group.label;
      if (label != null && label.isNotEmpty) {
        if (base == '조건 없음') {
          base = label;
        } else {
          base = '$label ($base)';
        }
      }

      // Add verification badge indicator if present
      if (verifIds.isNotEmpty) {
        return '$base +🛡️${verifIds.length}';
      }
      return base;
    }).toList();
  }
}

/// Database-specific helpers for [Event].
extension EventDbX on Event {
  /// Returns JSON suitable for insert/update operations.
  Map<String, dynamic> toDbJson() {
    return toJson()
      ..remove('id')
      ..remove('created_at')
      ..remove('updated_at');
  }
}
