import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:minglit_kit/src/data/models/party.dart';
import 'package:minglit_kit/src/data/models/party_entry_group.dart';
import 'package:minglit_kit/src/data/models/ticket.dart';

part 'event.freezed.dart';
part 'event.g.dart';

/// **Event Model**
///
/// Represents an actual instance of a party.
@freezed
abstract class Event with _$Event {
  const factory Event({
    required String id,
    @JsonKey(name: 'party_id') required String partyId,
    @JsonKey(name: 'start_time') required DateTime startTime,
    @JsonKey(name: 'end_time') required DateTime endTime,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
    @JsonKey(name: 'location_id') String? locationId,
    String? title,
    Map<String, dynamic>? description,
    @JsonKey(name: 'contact_options')
    @Default({})
    Map<String, dynamic> contactOptions,
    @JsonKey(name: 'max_participants') @Default(20) int maxParticipants,
    @JsonKey(name: 'current_participants') @Default(0) int currentParticipants,
    @Default('scheduled') String status,
    @JsonKey(includeToJson: false) Location? location,
    @JsonKey(includeToJson: false) Party? party,
    @JsonKey(includeToJson: false) List<Ticket>? tickets,
    @JsonKey(includeToJson: false) List<EntryGroup>? entryGroups,
  }) = _Event;

  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);

  /// Creates a fresh Event instance from a Party template.
  factory Event.createFromParty(
    Party party, {
    required DateTime startTime,
    required DateTime endTime,
  }) {
    final now = DateTime.now();
    return Event(
      id: '', // Generated by server
      partyId: party.id,
      startTime: startTime,
      endTime: endTime,
      createdAt: now,
      updatedAt: now,
      locationId: party.locationId,
      title: party.title,
      description: party.description != null
          ? Map<String, dynamic>.from(party.description!)
          : null,
      contactOptions: Map<String, dynamic>.from(party.contactOptions),
      maxParticipants: party.maxParticipants,
      entryGroups: party.entryGroups
          ?.map(EntryGroup.createFromTemplate)
          .toList(),
    );
  }
}

extension EventX on Event {
  // Replaced JSONB entryGroups with typed relational field
}

extension EventDbX on Event {
  Map<String, dynamic> toDbJson() {
    return toJson()
      ..remove('id')
      ..remove('created_at')
      ..remove('updated_at');
  }
}

/// **Event Application Model** (Pending/Approved)
@freezed
abstract class EventApplication with _$EventApplication {
  const factory EventApplication({
    required String id,
    @JsonKey(name: 'event_id') required String eventId,
    @JsonKey(name: 'ticket_id') required String ticketId,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
    @Default('pending') String status,
    String? message,
    // Relationships
    Event? event,
    Ticket? ticket,
  }) = _EventApplication;

  factory EventApplication.fromJson(Map<String, dynamic> json) =>
      _$EventApplicationFromJson(json);
}

/// **Event Participant Model** (Confirmed)
@freezed
abstract class EventParticipant with _$EventParticipant {
  const factory EventParticipant({
    required String id,
    @JsonKey(name: 'event_id') required String eventId,
    @JsonKey(name: 'ticket_id') required String ticketId,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
    @JsonKey(name: 'application_id') String? applicationId,
    @Default('ticket_issued') String status,
    @JsonKey(name: 'ticket_code') String? ticketCode,
  }) = _EventParticipant;

  factory EventParticipant.fromJson(Map<String, dynamic> json) =>
      _$EventParticipantFromJson(json);
}
