import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:minglit_kit/src/data/models/ticket_template.dart';

part 'ticket.freezed.dart';
part 'ticket.g.dart';

/// **Ticket Model**
///
/// Represents a ticket configuration for an event or a party template.
@freezed
abstract class Ticket with _$Ticket {
  const factory Ticket({
    required String id,
    required String name,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
    @JsonKey(name: 'event_id') String? eventId,
    String? description,
    @Default(0) int price,
    @Default(0) int quantity,
    @JsonKey(name: 'sold_count') @Default(0) int soldCount,
    @JsonKey(name: 'target_entry_group_ids')
    @Default([])
    List<String> targetEntryGroupIds,
    @JsonKey(name: 'required_verification_ids')
    @Default([])
    List<String> requiredVerificationIds,
    @Default('on_sale') String status,
  }) = _Ticket;

  factory Ticket.fromJson(Map<String, dynamic> json) => _$TicketFromJson(json);

  /// Creates a fresh Ticket instance from a TicketTemplate.
  /// Used when initializing an event creation form.
  factory Ticket.createFromTemplate(
    TicketTemplate template, {
    String eventId = '',
    String? id,
  }) {
    final now = DateTime.now();
    return Ticket(
      id: id ?? '', // New instance ID will be generated by DB if not provided
      name: template.name,
      description: template.description,
      price: template.price,
      quantity: template.quantity,
      targetEntryGroupIds: template.targetEntryGroupIds,
      requiredVerificationIds: template.requiredVerificationIds,
      createdAt: now,
      updatedAt: now,
      eventId: eventId,
    );
  }
}

extension TicketX on Ticket {
  // TicketX previously had gender/age label getters based on conditions.
  // Since conditions are removed, these are no longer relevant here.
  // They should be moved to PartyEntryGroup if not already there.
}

extension TicketDbX on Ticket {
  Map<String, dynamic> toDbJson({String? eventId}) {
    final json = toJson()
      ..remove('id')
      ..remove('created_at')
      ..remove('updated_at');

    if (eventId != null) {
      json['event_id'] = eventId;
    }
    return json;
  }
}
