import 'package:app_partner/src/features/party/detail/party_detail_controller.dart';
import 'package:minglit_kit/minglit_kit.dart' hide partyEventsProvider;
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'event_create_controller.g.dart';

@riverpod
class EventCreateController extends _$EventCreateController {
  @override
  FutureOr<void> build() {
    // Initial state is idle
  }

  Future<void> createEvent({
    required String partyId,
    required DateTime startTime,
    required DateTime endTime,
    required int maxParticipants,
    String? locationId,
    String? title,
  }) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final repo = ref.read(partyRepositoryProvider);

      final event = Event(
        id: '', // Generated by DB
        partyId: partyId,
        startTime: startTime,
        endTime: endTime,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        maxParticipants: maxParticipants,
        locationId: locationId,
        title: title,
      );

      await repo.createEvent(event);

      // Invalidate party events to refresh the list
      ref.invalidate(partyEventsProvider(partyId));
    });
  }
}
