name: minglit_lints
description: Custom lint rules for Minglit project to enforce UI consistency and design tokens.
version: 26.03.871-dev
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^8.0.0
  custom_lint_builder: 0.8.1
