-- Issue #2742: remove residual Metabase/Quartz/search-index tables that
-- still live in the exposed public schema and trigger Security Advisor
-- rls_disabled_in_public findings.
--
-- The prior 20260505000015 migration removed the first known Metabase
-- residue set. The 2026-05-23 advisor artifact found additional Metabase
-- app-db tables, Quartz scheduler tables, Metabase search indexes, and
-- semantic/metabot tables. They are external-tool operational state, not
-- Minglit runtime schema.
--
-- public.spatial_ref_sys is intentionally excluded: it is PostGIS extension
-- catalog data and remains documented as an extension exception.

DROP TABLE IF EXISTS
  public."moderation_review",
  public."qrtz_calendars",
  public."qrtz_fired_triggers",
  public."qrtz_locks",
  public."qrtz_paused_trigger_grps",
  public."qrtz_scheduler_state",
  public."search_index__gubiadnhjt7zp2k0fwrbv",
  public."bookmark_ordering",
  public."card_label",
  public."label",
  public."report_cardfavorite",
  public."collection_permission_graph_revision",
  public."dashboard_favorite",
  public."dashboardcard_series",
  public."report_dashboard",
  public."report_dashboardcard",
  public."application_permissions_revision",
  public."metric_important_field",
  public."persisted_info",
  public."qrtz_triggers",
  public."qrtz_blob_triggers",
  public."qrtz_cron_triggers",
  public."qrtz_simple_triggers",
  public."qrtz_simprop_triggers",
  public."qrtz_job_details",
  public."secret",
  public."sandboxes",
  public."report_card",
  public."http_action",
  public."search_index__s6pfttuvbpxatcpbikdjz",
  public."implicit_action",
  public."parameter_card",
  public."dashboard_tab",
  public."query_action",
  public."connection_impersonations",
  public."table_privileges",
  public."audit_log",
  public."recent_views",
  public."api_key",
  public."channel",
  public."cloud_migration",
  public."cache_config",
  public."query_table",
  public."query_field",
  public."notification",
  public."notification_handler",
  public."notification_recipient",
  public."channel_template",
  public."notification_subscription",
  public."search_index_metadata",
  public."user_key_value",
  public."notification_card",
  public."db_router",
  public."metabot",
  public."content_translation",
  public."metabot_prompt",
  public."metabot_conversation",
  public."metabot_message",
  public."semantic_search_token_tracking",
  public."data_edit_undo_chain",
  public."sequences",
  public."document_bookmark",
  public."document",
  public."transform_run_cancelation",
  public."transform_tag",
  public."transform_transform_tag",
  public."transform_job_transform_tag",
  public."transform_job_run",
  public."transform_job",
  public."comment_reaction",
  public."dependency",
  public."python_library",
  public."comment",
  public."support_access_grant_log",
  public."glossary",
  public."auth_identity",
  public."remote_sync_task",
  public."tenant",
  public."measure",
  public."remote_sync_object",
  public."analysis_finding_error",
  public."analysis_finding",
  public."transform",
  public."task_run",
  public."workspace",
  public."workspace_log",
  public."workspace_transform",
  public."workspace_input",
  public."workspace_merge_transform",
  public."workspace_output",
  public."workspace_merge",
  public."workspace_output_external",
  public."workspace_input_external",
  public."workspace_graph",
  public."premium_features_token_cache",
  public."transform_run",
  public."search_index__nnshf9k_gbbhi428mytzr",
  public."search_index__ls1noau6qfwura1z_qy1t"
CASCADE;
